"""
OpenAlex Constants and Domain Knowledge

Contains:
- RELEVANT_TOPIC_KEYWORDS: Keywords for soft-boosting by discipline
- DISCIPLINE_KEYWORDS: Keywords for discipline detection
- Core journals loading functionality
"""
import json
from pathlib import Path
from typing import Dict, List, Set

from app.core.logging import get_logger

logger = get_logger(__name__)


# Topics that indicate relevance for filtering (lowercase)
# Used for soft-boosting, not hard filtering
RELEVANT_TOPIC_KEYWORDS: Dict[str, List[str]] = {
    "developmental_psychology": [
        "developmental",
        "child",
        "infant",
        "toddler",
        "adolescent",
        "emotional development",
        "social development",
        "empathy",
        "kindness",
        "prosocial",
        "emotion regulation",
        "attachment",
        "parenting",
    ],
    "psychology": [
        "psychology",
        "child",
        "infant",
        "development",
        "emotion",
        "cognitive",
        "social",
        "mental",
    ],
    "medicine": [
        "medicine",
        "medical",
        "clinical",
        "health",
        "disease",
        "therapy",
        "diagnosis",
        "patient",
        "treatment",
        "surgery",
        "cardiology",
        "neurology",
        "oncology",
        "gastroenterology",
        "urology",
        "rheumatology",
        "epidemiology",
        "pharmacology",
        "pathology",
        "radiology",
        "internal medicine",
        "general practice",
        "vaccine",
    ],
    "computer_science": [
        "computer",
        "machine learning",
        "artificial intelligence",
        "software",
        "neural",
        "deep learning",
    ],
    "biology": [
        "biology",
        "molecular",
        "cell",
        "gene",
        "organism",
        "genetic",
        "crispr",
        "biotechnology",
    ],
    "physics": [
        "physics",
        "quantum",
        "particle",
        "optics",
        "condensed matter",
        "superconductor",
        "qubit",
    ],
    "chemistry": [
        "chemistry",
        "chemical",
        "catalyst",
        "synthesis",
        "electrochemical",
        "molecular",
        "compound",
    ],
    "economics": [
        "economics",
        "economic",
        "market",
        "financial",
        "monetary",
        "fiscal",
        "trade",
    ],
    "engineering": [
        "engineering",
        "structural",
        "civil",
        "mechanical",
        "construction",
        "seismic",
    ],
    "law": [
        "law",
        "legal",
        "court",
        "judicial",
        "statute",
        "rights",
        "constitutional",
    ],
    "literature": [
        "literature",
        "literary",
        "fiction",
        "novel",
        "postcolonial",
        "narrative",
        "poetry",
    ],
    "environmental_science": [
        "environmental",
        "climate",
        "ecology",
        "sustainability",
        "pollution",
        "carbon",
    ],
}


# Discipline detection keywords - more specific terms for accurate detection
DISCIPLINE_KEYWORDS: Dict[str, List[str]] = {
    "developmental_psychology": [
        "child development",
        "infant development",
        "toddler",
        "infancy",
        "early childhood",
        "developmental psychology",
        "social-emotional development",
        "emotional development",
        "empathy",
        "kindness",
        "prosocial",
        "emotion regulation",
        "attachment theory",
        "parenting",
        "caregiver",
        "temperament",
        "conscience development",
        "sert",
        "developmental assessment",
        "psychometric",
        "validation study",
        "cfa",
        "confirmatory factor",
        "sem",
        "structural equation",
    ],
    "psychology": [
        "cognitive",
        "mental health",
        "psychological",
        "emotion",
        "perception",
        "child development",
        "infant",
        "toddler",
        "empathy",
        "kindness",
        "prosocial",
        "emotional regulation",
        "social-emotional",
        "developmental psychology",
        "psychometric",
        "validation study",
        "questionnaire",
        "therapy session",
        "counseling",
        "psychotherapy",
        "anxiety disorder",
        "depression",
        "ptsd",
        "personality",
        "social psychology",
    ],
    "medicine": [
        "clinical",
        "patient",
        "treatment",
        "disease",
        "diagnosis",
        "medical",
        "health",
        "therapy",
        "cancer",
        "tumor",
        "CT scan",
        "meta-analysis",
        "systematic review",
        "randomized controlled",
        "cohort study",
        "case-control",
        "clinical trial",
        "retrospective",
        "syndrome",
        "fibromyalgia",
        "chronic pain",
        "arthritis",
        "diabetes",
        "hypertension",
        "cardiovascular",
        "stroke",
        "obesity",
        "inflammation",
        "autoimmune",
        "bladder",
        "urinary",
        "kidney",
        "renal",
        "liver",
        "hepatic",
        "cardiac",
        "heart",
        "lung",
        "pulmonary",
        "gastrointestinal",
        "neurological",
        "musculoskeletal",
        "endocrine",
        "prevalence",
        "incidence",
        "association",
        "comorbidity",
        "epidemiology",
        "mortality",
        "morbidity",
        "risk factor",
        "drug",
        "medication",
        "pharmaceutical",
        "surgery",
        "surgical",
        "transplant",
        "chemotherapy",
        "radiotherapy",
        "vaccine",
        "mrna",
        "immunization",
        "antibody",
    ],
    "computer_science": [
        "machine learning",
        "neural network",
        "software",
        "database",
        "deep learning",
        "convolutional neural",
        "artificial intelligence",
        "natural language processing",
        "computer vision",
        "reinforcement learning",
        "transformer model",
        "bert",
        "gpt",
        "classification model",
        "prediction model",
        "cnn",
        "image recognition",
        "object detection",
        "nlp",
        "programming",
        "code",
        "api",
        "computing",
    ],
    "biology": [
        "cell",
        "gene",
        "protein",
        "organism",
        "species",
        "evolution",
        "molecular biology",
        "dna",
        "rna",
        "genomic",
        "transcriptome",
        "crispr",
        "genome editing",
        "genetic",
        "plant biology",
        "microbiome",
        "microbial",
        "bacteria",
        "virus",
        "ecosystem",
        "biodiversity",
        "ecology",
        "biotechnology",
        "bioinformatics",
    ],
    "physics": [
        "quantum",
        "particle physics",
        "electron",
        "photon",
        "quantum mechanics",
        "quantum entanglement",
        "superconducting",
        "qubit",
        "magnetic field",
        "electromagnetic",
        "optics",
        "thermodynamics",
        "relativity",
        "gravitational",
        "nuclear",
        "plasma",
        "condensed matter",
        "semiconductor",
        "laser",
        "wave function",
        "schrödinger",
        "heisenberg",
        "boson",
        "fermion",
        "atomic",
        "subatomic",
        "hadron",
        "collider",
        "accelerator",
        "topological",
        "insulator",
        "superconductor",
        "cryogenic",
    ],
    "chemistry": [
        "chemical reaction",
        "compound",
        "molecule",
        "synthesis",
        "catalyst",
        "electrochemical",
        "organic chemistry",
        "inorganic",
        "polymer",
        "spectroscopy",
        "chromatography",
        "oxidation",
        "reduction",
        "catalysis",
        "nanomaterial",
        "graphene",
        "carbon nanotube",
        "electrochemistry",
        "photochemistry",
        "biochemistry",
        "co2 reduction",
        "carbon dioxide",
        "electrolysis",
    ],
    "economics": [
        "market",
        "economic",
        "financial",
        "trade",
        "investment",
        "monetary policy",
        "inflation",
        "gdp",
        "fiscal",
        "macroeconomic",
        "microeconomic",
        "econometric",
        "price",
        "supply demand",
        "banking",
        "currency",
        "stock market",
        "cost-effectiveness",
        "health economics",
        "welfare",
    ],
    "engineering": [
        "mechanical engineering",
        "electrical engineering",
        "structural",
        "civil engineering",
        "earthquake",
        "seismic",
        "bridge",
        "construction",
        "building materials",
        "concrete",
        "steel",
        "composite material",
        "aerodynamic",
        "thermodynamic",
        "robotics",
        "automation",
        "control system",
        "manufacturing",
        "sustainable materials",
        "earthquake-resistant",
    ],
    "law": [
        "legal",
        "law",
        "jurisprudence",
        "court",
        "statute",
        "judicial",
        "constitutional",
        "legislation",
        "rights",
        "attorney",
        "lawsuit",
        "litigation",
        "contract law",
        "criminal law",
        "civil law",
        "privacy law",
        "regulation",
        "compliance",
        "intellectual property",
        "patent",
        "harvard law",
        "stanford law",
        "yale law",
    ],
    "literature": [
        "literature",
        "fiction",
        "novel",
        "poetry",
        "narrative",
        "postcolonial",
        "literary",
        "prose",
        "drama",
        "playwright",
        "african fiction",
        "modernist",
        "postmodernist",
        "feminist",
        "comparative literature",
        "literary criticism",
        "author",
        "pmla",
        "short story",
        "memoir",
    ],
    "environmental_science": [
        "climate",
        "pollution",
        "carbon capture",
        "environmental",
        "sustainability",
        "ecology",
        "conservation",
        "renewable",
        "emission",
        "greenhouse",
        "carbon footprint",
        "biodegradable",
        "recycling",
        "waste management",
        "air quality",
        "water quality",
        "deforestation",
        "ecosystem",
        "climate change",
        "global warming",
    ],
}


# Discipline-specific key journals for proactive injection
# These are journals that MUST appear for specific disciplines
KEY_JOURNALS_BY_DISCIPLINE: Dict[str, List[str]] = {
    "developmental_psychology": [
        "Child Development",
        "Developmental Psychology",
        "Infant Behavior and Development",
        "Social Development",
        "Developmental Science",
        "Journal of Child Psychology and Psychiatry",
        "Journal of Experimental Child Psychology",
        "British Journal of Developmental Psychology",
        "Frontiers in Psychology",
        "Journal of Personality Assessment",
    ],
    "psychology": [
        "Psychological Review",
        "Journal of Abnormal Psychology",
        "Developmental Psychology",
        "Journal of Consulting and Clinical Psychology",
        "Child Development",
        "Psychological Science",
        "Frontiers in Psychology",
        "PLOS ONE",
        "Journal of Personality and Social Psychology",
        "Cognition and Emotion",
    ],
    "medicine": [
        "New England Journal of Medicine",
        "The Lancet",
        "JAMA",
        "BMJ",
        "Annals of Internal Medicine",
    ],
    "computer_science": [
        "Nature Machine Intelligence",
        "IEEE Transactions on Pattern Analysis and Machine Intelligence",
        "Journal of Machine Learning Research",
        "Artificial Intelligence",
        "Neural Computation",
    ],
}


def load_core_journals() -> Set[str]:
    """
    Load core journals list from JSON file.

    Returns:
        Set of normalized journal names for boosting.
    """
    core_journals: Set[str] = set()

    try:
        data_path = Path(__file__).parent.parent.parent / "data" / "core_journals.json"
        if data_path.exists():
            with open(data_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                for discipline in data.get("disciplines", []):
                    for journal in discipline.get("journals", []):
                        name = journal.get("title", "")
                        # Normalize: lowercase, alphanumeric only
                        normalized = "".join(
                            c.lower() for c in name if c.isalnum() or c.isspace()
                        )
                        core_journals.add(" ".join(normalized.split()))
            logger.info(f"Loaded {len(core_journals)} core journals for boosting.")
    except Exception as e:
        logger.warning(f"Failed to load core journals: {e}")

    return core_journals


def get_key_journals_for_discipline(discipline: str) -> List[str]:
    """
    Get key journals that should appear for a specific discipline.

    Args:
        discipline: Detected discipline name.

    Returns:
        List of journal names to proactively search for.
    """
    # Direct match
    if discipline in KEY_JOURNALS_BY_DISCIPLINE:
        return KEY_JOURNALS_BY_DISCIPLINE[discipline]

    # Fallback to general psychology for sub-disciplines
    if "psychology" in discipline:
        return KEY_JOURNALS_BY_DISCIPLINE.get("psychology", [])

    return []
